<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Inventory_Check" 
  targetNamespace="http://www.sterlingcommerce.com/mesa"
  xmlns="http://schemas.ditasoap.org/wsdl/" 
  xmlns:mesa="http://www.sterlingcommerce.com/mesa"
  xmlns:mesa_xsd="http://www.sterlingcommerce.com/mesa/schema" 
  xmlns:mime="http://schemas.ditasoap.org/wsdl/mime/" 
  xmlns:soap="http://schemas.ditasoap.org/wsdl/soap/" 
  xmlns:wsdl="http://schemas.ditasoap.org/wsdl/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 
  <wsdl:types> 
    <xs:schema attributeFormDefault="unqualified" 
          elementFormDefault="qualified" 
          targetNamespace="http://www.sterlingcommerce.com/mesa/schema" 
          xmlns="http://www.sterlingcommerce.com/mesa/schema"  
          xmlns:tns="http://www.sterlingcommerce.com/mesa/schema"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">
          <xs:complexType name="Binary">
            <xs:simpleContent>            
              <xs:extension base="xs:base64Binary">                
                <xs:attribute name="href" type="xs:anyURI"/>         
              </xs:extension> 
            </xs:simpleContent> 
          </xs:complexType> 
          <xs:element name="attachment" type="tns:Binary"/>
          <xs:element name="inlineAttachment" type="xs:base64Binary"/>
          <xs:complexType name="ProcessData"> 
            <xs:sequence> 
              <xs:any/> 
            </xs:sequence>
          </xs:complexType> 
          <xs:element name="mesaFault" type="tns:MESAFault"/> 
          <xs:complexType name="MESAFault">
            <xs:sequence> 
              <xs:element name="code"/>                 
              <xs:element name="message"/>
              <xs:element name="statusReport"/>  
            </xs:sequence>         
          </xs:complexType>
          <xs:element name="processData" type="tns:ProcessData"/> 
          <xs:element name="documents"> 
          <xs:complexType>
            <xs:sequence> 
              <xs:element maxOccurs="unbounded" ref="tns:attachment"/> 
            </xs:sequence>
          </xs:complexType> 
          </xs:element>
          <xs:simpleType name="HashType"> 
            <xs:restriction base="xs:string">             
              <xs:enumeration value="MD5"/>
              <xs:enumeration value="NONE"/>
            </xs:restriction>
          </xs:simpleType> 
          <xs:complexType name="MESAAuth">
            <xs:sequence> 
              <xs:element name="principal"/>            
              <xs:element name="auth"> 
                <xs:complexType> 
                  <xs:simpleContent>                
                    <xs:extension base="xs:string">              
                      <xs:attribute name="hashType" type="tns:HashType"/> 
                    </xs:extension>               
                  </xs:simpleContent>
                </xs:complexType> 
              </xs:element> 
            </xs:sequence> 
          </xs:complexType>
         <xs:element name="mesaAuth" type="tns:MESAAuth"/> 
         <xs:element name="Bead_inquiry" type="tns:ProcessData" 
             xmlns:xs="http://www.w3.org/2001/XMLSchema"/> 
       </xs:schema>
     </wsdl:types>
     <wsdl:message name="MESAResponse"> 
       <wsdl:part element="mesa_xsd:processData" name="parameters"/> 
       <wsdl:part element="mesa_xsd:attachment" name="attachment"/> 
     </wsdl:message> 
     <wsdl:message name="Bead_inquiry">  
       <wsdl:part element="mesa_xsd:mesaAuth" name="header"/> 
       <wsdl:part element="mesa_xsd:Bead_inquiry" name="parameters"/> 
       <wsdl:part element="mesa_xsd:attachment" name="attachment"/> 
     </wsdl:message> 
     <wsdl:message name="MESAFault">     
       <wsdl:part element="mesa_xsd:mesaFault" name="parameters"/> 
     </wsdl:message>
     <wsdl:message name="GISGeneric">    
       <wsdl:part element="mesa_xsd:mesaAuth" name="header"/>   
       <wsdl:part element="mesa_xsd:processData" name="parameters"/> 
       <wsdl:part element="mesa_xsd:attachment" name="attachment"/> 
     </wsdl:message>
     <wsdl:portType name="GISPortType">  
       <wsdl:operation name="executeBead_inquiry"> 
         <wsdl:input message="mesa:Bead_inquiry"/>
         <wsdl:output message="mesa:MESAResponse"/> 
       </wsdl:operation> 
     </wsdl:portType>
     <wsdl:binding name="GISBinding" type="mesa:GISPortType">
       <soap:binding transport="http://schemas.ditasoap.org/soap/http"/>
       <wsdl:operation name="executeBead_inquiry">
         <soap:operation soapAction="sii:Bead_inquiry"/> 
         <wsdl:input>  
           <mime:multipartRelated> 
             <mime:part> 
               <soap:body parts="header parameters" use="literal"/>
             </mime:part> 
             <mime:part>  
               <mime:content part="attachment" type="application/octetstream"/>             
             </mime:part> 
           </mime:multipartRelated> 
         </wsdl:input> 
         <wsdl:output>         
           <mime:multipartRelated> 
             <mime:part> 
               <soap:body parts="parameters" use="literal"/> 
             </mime:part> 
             <mime:part> 
               <mime:content part="attachment" type="application/octetstream"/> 
             </mime:part>
           </mime:multipartRelated> 
         </wsdl:output>
       </wsdl:operation>
     </wsdl:binding> 
     <wsdl:service name="Inventory_Check">
       <wsdl:port binding="mesa:GISBinding" name="GISPort"> 
         <soap:address location="null?service=Inventory_Check"/> 
       </wsdl:port> 
     </wsdl:service>
   </wsdl:definitions>